name: gogo_riders_delivery
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.13
  # CONNECTIVITY
  url_launcher: ^6.1.11
  package_info_plus: ^4.0.2
  intl: ^0.18.1
  html: ^0.15.4
  http: ^1.0.0
  connectivity_plus: ^4.0.1
  dio: ^4.0.0

  # STATE MANAGEMENT
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5

  # Base
  nb_utils: ^5.0.8
  google_fonts: ^5.1.0
  animated_bottom_navigation_bar: ^1.2.0

  # TOOLS
  cupertino_icons: ^1.0.5
  js: ^0.6.4
  lottie: ^2.4.0
  timeline_tile: ^2.0.0
  country_code_picker: ^3.0.0

  # Dotted Line
  dotted_line: ^3.2.2

  # Payment gateway
  flutter_stripe: ^9.2.2
  razorpay_flutter: ^1.3.5
  flutterwave_standard: ^1.0.8
  paytm: ^3.0.1
  flutter_paystack: ^1.0.7
  flutter_braintree: ^3.0.0
#  mercado_pago_mobile_checkout: ^0.1.1
  flutter_paytabs_bridge: ^2.4.3
  my_fatoorah: ^3.3.0

  # IMAGES
  image_picker: ^0.8.9
  file_picker: ^5.3.2
  cached_network_image: ^3.2.3
  syncfusion_flutter_signaturepad: ^22.1.34
  screenshot: ^2.1.0
  date_time_picker: ^2.1.0

  # MAP
  geolocator: ^9.0.2
  google_maps_flutter: ^2.3.1
  flutter_polyline_points: ^1.0.0
  maps_launcher: ^2.2.0
  google_maps_place_picker_mb: ^3.0.2

  # PUSH NOTIFICATION
  onesignal_flutter: ^3.5.1

  #OTP TEXTFIELD
  otp_text_field: ^1.1.3

  #FIREBASE
  firebase_crashlytics: ^3.3.3
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.3
  firebase_database: ^10.2.3
  paginate_firestore: ^1.0.3+1
  cloud_firestore: ^4.8.1

  # DOWNLOAD INVOICE PDF
  pdf: ^3.10.4
  path_provider: ^2.0.15
  open_file: ^3.3.2
  printing: ^5.11.0

  # READ MORE LESS
  readmore: ^2.2.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  mobx_codegen: ^2.3.0
  build_web_compilers: ^4.0.4



dependency_overrides:
  intl: ^0.18.0
  http: ^0.13.5
  connectivity_plus: ^3.0.3
  freezed_annotation: ^2.2.0
  cloud_firestore: ^4.8.1

  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/flag/

