# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '13.2'
target 'OneSignalNotificationServiceExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps', '7.1.0'
  pod 'FirebaseFirestore'
  # Pods for OneSignalNotificationServiceExtension

end

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps', '7.1.0'
  pod 'FirebaseFirestore'
  # Pods for Runner

end
